# Generated by Django 4.0 on 2023-06-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cliente',
            new_name='cliente_id',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='habitacion',
            new_name='habitacion_id',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='num_tarjeta',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pago_choices',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_pago',
            field=models.CharField(choices=[('Tarjeta Debito', 'TARJETA DEBITO'), ('Tarjeta Credito', 'TARJETA CREDITO'), ('Efectivo', 'EFECTIVO')], default='Efectivo', max_length=30),
        ),
    ]
