# Generated by Django 4.0 on 2022-09-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='activo',
            new_name='estado',
        ),
    ]
