# Generated by Django 4.0 on 2022-12-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_rename_activo_habitacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='activo',
            field=models.CharField(choices=[('Disponible', 'DISPONIBLE'), ('Reservada', 'RESERVADA'), ('Fuera_de_Servicio', 'FUERA_DE_SERVICIO')], default='Disponible', max_length=30),
        ),
    ]
