# Generated by Django 4.0 on 2024-04-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_rename_nombre_alojamiento_habitacion_alojamiento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='activo',
        ),
    ]
