# Generated by Django 4.0 on 2023-02-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='identificacion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_identificacion',
            field=models.CharField(default='000-000000-0000A', max_length=30),
        ),
    ]
