# Generated by Django 4.0 on 2024-01-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
