# Generated by Django 4.0 on 2024-05-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
